### ISSUE TITLE
Hamburger menu icon not rotating

### ISSUE THREAD

**Issue by mikef80** [tommo593/portfolio-vite#1]
Hi.

Just took a look at your site and noticed in smaller screens, you default to a hamburger menu.

When you click the menu to open, the hamburger rotates, but it doesn't rotate back again when you close the menu. I just think this would improve the UI/UX a bit.

Hope that's OK!

**Comment by tommo593** [comment]
I believe this is now solved. Thanks!

**Comment by mikef80** [comment]
No worries! Looks good now.
